os:
  - linux
  - osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == osx ]]; then
      brew install bats
    else
    sudo apt-get update -q
      sudo apt-get install -y bats
    fi

script:
  - bats tests/
